/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // devSideBar: {
  //   'Developpers':[{type: 'autogenerated', dirName: 'developpers'}]
  // },
  // consumersSideBar: {
  //   'Consumers':[{type: 'autogenerated', dirName: 'consumers'}]
  // },

  devSidebar: [
    {
      type: 'autogenerated',
      dirName: 'developpers',
    },
    {
      type: 'category',
      label: 'Ressources',
      link: {type: 'doc', id: 'external/external'},
      items: ['external/docker', 'external/repos'],
    },
    // {
    //   type: 'autogenerated',
    //   dirName: 'api', // Generate sidebar slice from docs/api
    // },
    // {
    //   type: 'category',
    //   label: 'Community',
    //   items: ['team', 'chat'],
    // },
  ],
  consumersSidebar: [
    {
      type: 'autogenerated',
      dirName: 'consumers',
    },
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
