/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "LinTO documentation",
  "tagline": "Your open source end-to-end platform for voice-operated solutions",
  "url": "https://doc.linto.ai",
  "baseUrl": "/fr/",
  "onBrokenLinks": "ignore",
  "onBrokenMarkdownLinks": "ignore",
  "favicon": "img/favicon.ico",
  "organizationName": "linto-ai",
  "projectName": "documentation-website",
  "trailingSlash": false,
  "deploymentBranch": "deployment",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "fr"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/yhoupert/Work/linto/dev_v2/doc/documentation-website/sidebars.js",
          "editUrl": "https://github.com/linto-ai/documentation-website/tree/source/"
        },
        "blog": {
          "showReadingTime": true,
          "routeBasePath": "/tutorials",
          "path": "tutorials",
          "editUrl": "https://github.com/linto-ai/documentation-website/tree/source/tutorials"
        },
        "theme": {
          "customCss": "/home/yhoupert/Work/linto/dev_v2/doc/documentation-website/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "Handbooks ",
      "logo": {
        "alt": "LinTO",
        "src": "img/linto.svg"
      },
      "items": [
        {
          "to": "/docs/consumers",
          "label": "For consumers",
          "position": "left"
        },
        {
          "to": "/docs/developpers",
          "label": "For developpers",
          "position": "left"
        },
        {
          "to": "tutorials",
          "label": "Tutorials",
          "position": "left"
        },
        {
          "href": "https://github.com/linto-ai",
          "label": "GitHub",
          "className": "navbar__item navbar__link header-github-link",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Developper's docs",
          "items": [
            {
              "label": "Cognitive APIs",
              "to": "/docs/developpers/apis"
            },
            {
              "label": "Virtual Agents and Smart Assistants",
              "to": "/docs/developpers/agent"
            },
            {
              "label": "Smart Conversations",
              "to": "/docs/developpers/meeting"
            },
            {
              "label": "Tutorials",
              "to": "/tutorials"
            }
          ]
        },
        {
          "title": "LinTO Live",
          "items": [
            {
              "label": "Browser demos",
              "to": "https://linagora.com/fr/produits/linto/"
            },
            {
              "label": "Conversation Manager",
              "to": "https://convos.linto.ai/"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discord",
              "href": "https://discord.gg/jvNK3FXv3d"
            },
            {
              "label": "Contact",
              "to": "https://linto.ai/#contact"
            }
          ]
        },
        {
          "title": "Links",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/linto-ai"
            },
            {
              "label": "LinTO HomePage",
              "href": "https://linto.ai"
            },
            {
              "label": "LINAGORA",
              "href": "https://linagora.com"
            },
            {
              "label": "LINAGORA Labs - Meet the LinTO team",
              "href": "https://labs.linagora.com"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2022 LINAGORA"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
